backend:
  name: github
  repo: techmilldenton/flintconf
  branch: master # Branch to update (optional; defaults to master)
  site_domain: flint.stokedenton.com

# This line should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "speakers" # Used in routes, e.g., /admin/collections/blog
    label: "Speakers" # Used in the UI
    folder: "_speakers" # The path to the folder where the documents are stored
    identifier_field: name
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "company_title", widget: "string"}
      - {label: "Company", name: "company_name", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string", required: false }
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - label: "Year"
        name: "year"
        widget: "select"
        default: ["2019"]
        required: false
        options: ["2019", "2020"]
  - name: "topics" # Used in routes, e.g., /admin/collections/blog
    label: "Topics" # Used in the UI
    folder: "_topics" # The path to the folder where the documents are stored
    identifier_field: title
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Time", name: "time", widget: "string"}
      - {label: "Breakout", name: "breakout", widget: "boolean", required: false}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 10, valueType: "int", min: 1, max: 100}
      - label: "Color"
        name: "color"
        widget: "select"
        required: false
        options:
          - { label: "Primary (purple?)", value: "primary" }
          - { label: "Secondary (gray?)", value: "secondary" }
          - { label: "Green", value: "success" }
          - { label: "Orange", value: "warning" }
          - { label: "Red", value: "danger" }
          - { label: "Blue", value: "info" }
          - { label: "White", value: "light" }
          - { label: "Black", value: "dark" }
      - {label: "Speaker", name: "speaker", widget: "relation", collection: "speakers", searchFields: ["name", "twitter"], valueField: "name", displayFields: ["name"], required: false}
  - name: "sponsors" # Used in routes, e.g., /admin/collections/blog
    label: "Sponsor" # Used in the UI
    folder: "_sponsors" # The path to the folder where the documents are stored
    identifier_field: title
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Facebook", name: "facebook", widget: "string", default: "https://wwww.facebook.com/stokedenton", required: false}
      - {label: "Twitter", name: "twitter", widget: "string", default: "https://twitter.com/stokedenton", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", default: "https://wwww.instagram.com/stokedenton", required: false}
      - {label: "Order", name: "order_sort", widget: "number", default: 10, valueType: "int", min: 1, max: 100}
  - name: "features" # Used in routes, e.g., /admin/collections/blog
    label: "Feature" # Used in the UI
    folder: "_features" # The path to the folder where the documents are stored
    identifier_field: title
    create: true # Allow users to create new documents in this collection
    slug: "features-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    output: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "carousel"
    label: "Carousels"
    folder: "_carousel"
    identifier_field: name
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "name"
        widget: "string"
        hint: "Any descriptive title will work here."
      - label: Alternative text / Caption
        name: "alt"
        widget: "string"
        hint: "Alt tag text that's also used as an image caption"
        required: false
      - label: "Image source"
        name: "src"
        widget: "image"  